# Generated by Django 5.1.1 on 2024-09-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_task_start_date_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('I', 'Inicializado'), ('E', 'Em Andamento'), ('F', 'Finalizado')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tarefa.task')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=70)),
                ('tasks', models.ManyToManyField(related_name='tags', to='tarefa.task')),
            ],
        ),
    ]
