# Generated by Django 5.1.1 on 2024-10-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0004_comment_fk_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='fk_user',
        ),
    ]
